### ISSUE TITLE
Plugin 1v1

### ISSUE THREAD

**Issue by ghost** [KyleTheHack3r/PM-Plugins#1]
1v1 plugin still crash my server. The console displays this message : Parse error: syntax error, unexpected '$game' (T_VARIABLE), expecting function (T_FUNCTION) in phar:///home/gsp_20/151.80.76.69-19147/plugins/phar_1v1_Fombnlakxk31dP1.phar/src/onevone/MainClass.php on line 14

**Comment by ghost** [comment]
.... It Isnt Ready

**Comment by KyleTheHack3r** [comment]
It sort of is. Just need to learn Git so I can push a commit.

**Comment by ghost** [comment]
Oooo Gimmmmmme

**Comment by KyleTheHack3r** [comment]
By sort of, I mean I've added 100 lines of code that makes it look like it works.

I've still to add an invitation system eg, "/1v1 (name)".
